name: services/chat

on:
  push:
    branches:
    - "main"
    paths:
    - 'backend-end/services/chat/**'
    
  pull_request:
    branches:
    - "main"

jobs:
  build-docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub Registry
      run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build the tagged Docker image
      run: docker build -t me .
    - name: Tag the image
      run: docker tag me:latest me:${{steps.vars.outputs.tag}} 276499450488.dkr.ecr.us-east-2.amazonaws.com/me:latest
    - name: Push the tagged Docker image
      run: docker push 276499450488.dkr.ecr.us-east-2.amazonaws.com/me:latest
