name: Frontend Shell

on:
  push:
    branches:
    - "main"
    paths:
    - 'front-end/shell/**'
    
  pull_request:
    branches:
    - "main"
    

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install dependencies
      working-directory: ./front-end/shell
      run: npm install

    - name: Lint
      working-directory: ./front-end/shell
      run: npm run lint

    - name: Test
      working-directory: ./front-end/shell
      run: npm run test

    - name: Build
      working-directory: ./front-end/shell
      run: npm run build

